// Code generated by "stringer -type=TokenType -output=token_type_string.go"; DO NOT EDIT.

package cask

import "fmt"

const _TokenType_name = "EOFILLEGALCONSTGLOBALIDENTINTSTRINGSYMBOLPNREGEXPPNSTARTPNENDASSIGNASTERISKBANGMINUSPLUSSLASHMODULUSEQGTLTNOTEQCOMMANEWLINESEMICOLONCOLONDOTLBRACELBRACKETLPARENPIPERBRACERBRACKETRPARENSCOPEREGEXPCLASSDEFDOELSEELSEIFENDFALSEIFMODULENILRETURNSELFTHENTRUEYIELD"

var _TokenType_index = [...]uint16{0, 3, 10, 15, 21, 26, 29, 35, 41, 49, 56, 61, 67, 75, 79, 84, 88, 93, 100, 102, 104, 106, 111, 116, 123, 132, 137, 140, 146, 154, 160, 164, 170, 178, 184, 189, 195, 200, 203, 205, 209, 215, 218, 223, 225, 231, 234, 240, 244, 248, 252, 257}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return fmt.Sprintf("TokenType(%d)", i)
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
