// Code generated by "stringer -type=TokenType -output=token_type_string.go"; DO NOT EDIT.

package cask

import "fmt"

const _TokenType_name = "EOFILLEGALCONSTGLOBALIDENTINTSTRINGSYMBOLASSIGNASTERISKBANGMINUSPLUSSLASHEQGTLTNOTEQCOMMANEWLINESEMICOLONCOLONDOTLBRACELBRACKETLPARENPIPERBRACERBRACKETRPARENSCOPECLASSDEFDOELSEENDFALSEIFMODULENILRETURNSELFTHENTRUEYIELD"

var _TokenType_index = [...]uint8{0, 3, 10, 15, 21, 26, 29, 35, 41, 47, 55, 59, 64, 68, 73, 75, 77, 79, 84, 89, 96, 105, 110, 113, 119, 127, 133, 137, 143, 151, 157, 162, 167, 170, 172, 176, 179, 184, 186, 192, 195, 201, 205, 209, 213, 218}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return fmt.Sprintf("TokenType(%d)", i)
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
